<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <!-- What every shipped package carries. -->

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Authors>TriasDev GmbH &amp; Co. KG</Authors>
    <Company>TriasDev GmbH &amp; Co. KG</Company>
    <Copyright>Copyright © 2026 TriasDev GmbH &amp; Co. KG</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
